name: "Bug Report "
title: "Bug: "
description: Bugs Report About GitHub Issue Template Generator
body:
  - type: input
    id: web-browser
    attributes:
      label: Web Browser
      description: Web Browser Where the error occur on
  - type: textarea
    id: error-description
    attributes:
      label: Describe the error
