name: "Bug Report "
title: "Bug: "
description: Bugs Report About GitHub Issue Template Generator
body:
  - type: textarea
    id: textarea
    attributes:
      label: Web Browser
      description: Web Browser Where the error occur on
  - type: textarea
    id: textarea
    attributes:
      label: Describe the error
