name: Feature Request
title: "(Feature Request 🧪): "
description: Request Additional or Missing Features
label: feature-request
body:
  - type: textarea
    id: textarea-0
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
  - type: textarea
    id: textarea-1
    attributes:
      label: Describe the solution you'd like
      description: What would you like to happen? Be specific.
  - type: textarea
    id: textarea-2
    attributes:
      label: Describe alternatives you've considered
  - type: checkboxes
    id: checkboxes-3
    attributes:
      label: Are you willing to Contribute to this feature?
